# Generated by Django 4.2.2 on 2023-06-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="pets_allowed",
            field=models.BooleanField(default=True),
        ),
    ]
