# Generated by Django 4.2.2 on 2023-06-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_house_pets_allowed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="house",
            old_name="price",
            new_name="price_per_night",
        ),
    ]
